-- ============================================================================
--  PostgreSQL 16 - esquema del banco de pruebas NL2SQL (dataset e-commerce)
--  Se ejecuta como superusuario contra POSTGRES_DB (testdb) en el PRIMER
--  arranque del contenedor. Idempotente (CREATE TABLE IF NOT EXISTS).
--
--  8 tablas:
--    categories 1--N products
--    customers  1--N addresses
--    customers  1--N orders
--    orders     1--N order_items   N--1 products
--    orders     1--N payments
--    orders     1--N shipments
-- ============================================================================

-- ----------------------------------------------------------------------------
-- categories
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
    category_id  INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(80)  NOT NULL,
    description  VARCHAR(255),
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_categories_name UNIQUE (name)
);

-- ----------------------------------------------------------------------------
-- customers
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customers (
    customer_id       INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name        VARCHAR(60)  NOT NULL,
    last_name         VARCHAR(60)  NOT NULL,
    email             VARCHAR(180) NOT NULL,
    phone             VARCHAR(30),
    date_of_birth     DATE,
    registration_date DATE         NOT NULL,
    status            VARCHAR(10)  NOT NULL DEFAULT 'ACTIVE',
    country           VARCHAR(60)  NOT NULL,
    city              VARCHAR(80)  NOT NULL,
    CONSTRAINT uq_customers_email  UNIQUE (email),
    CONSTRAINT ck_customers_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- ----------------------------------------------------------------------------
-- addresses
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS addresses (
    address_id   INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  INTEGER      NOT NULL,
    address_type VARCHAR(10)  NOT NULL,
    address_line VARCHAR(160) NOT NULL,
    city         VARCHAR(80)  NOT NULL,
    state        VARCHAR(80),
    postal_code  VARCHAR(20),
    country      VARCHAR(60)  NOT NULL,
    is_default   BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_addresses_customer
        FOREIGN KEY (customer_id) REFERENCES customers (customer_id),
    CONSTRAINT ck_addresses_type
        CHECK (address_type IN ('BILLING', 'SHIPPING', 'HOME'))
);

-- ----------------------------------------------------------------------------
-- products
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
    product_id  INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER       NOT NULL,
    name        VARCHAR(140)  NOT NULL,
    description VARCHAR(400),
    price       NUMERIC(10,2) NOT NULL,
    stock       INTEGER       NOT NULL DEFAULT 0,
    status      VARCHAR(12)   NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES categories (category_id),
    CONSTRAINT ck_products_price  CHECK (price >= 0),
    CONSTRAINT ck_products_stock  CHECK (stock >= 0),
    CONSTRAINT ck_products_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'DISCONTINUED'))
);

-- ----------------------------------------------------------------------------
-- orders
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
    order_id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id         INTEGER       NOT NULL,
    order_date          TIMESTAMPTZ   NOT NULL,
    status              VARCHAR(12)   NOT NULL,
    subtotal            NUMERIC(12,2) NOT NULL DEFAULT 0,
    tax                 NUMERIC(12,2) NOT NULL DEFAULT 0,
    shipping_cost       NUMERIC(12,2) NOT NULL DEFAULT 0,
    total               NUMERIC(12,2) NOT NULL DEFAULT 0,
    shipping_address_id INTEGER,
    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id) REFERENCES customers (customer_id),
    CONSTRAINT fk_orders_address
        FOREIGN KEY (shipping_address_id) REFERENCES addresses (address_id),
    CONSTRAINT ck_orders_status CHECK (status IN
        ('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    CONSTRAINT ck_orders_amounts CHECK (subtotal >= 0 AND tax >= 0 AND shipping_cost >= 0 AND total >= 0)
);

-- ----------------------------------------------------------------------------
-- order_items  (tabla intermedia orders <-> products)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_items (
    order_item_id INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      INTEGER       NOT NULL,
    product_id    INTEGER       NOT NULL,
    quantity      INTEGER       NOT NULL,
    unit_price    NUMERIC(10,2) NOT NULL,
    discount      NUMERIC(10,2) NOT NULL DEFAULT 0,
    subtotal      NUMERIC(12,2) NOT NULL,
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders (order_id),
    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id) REFERENCES products (product_id),
    CONSTRAINT uq_order_items_order_product UNIQUE (order_id, product_id),
    CONSTRAINT ck_order_items_qty      CHECK (quantity > 0),
    CONSTRAINT ck_order_items_prices   CHECK (unit_price >= 0 AND discount >= 0 AND subtotal >= 0)
);

-- ----------------------------------------------------------------------------
-- payments
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payments (
    payment_id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id              INTEGER       NOT NULL,
    payment_date          TIMESTAMPTZ   NOT NULL,
    payment_method        VARCHAR(20)   NOT NULL,
    amount                NUMERIC(12,2) NOT NULL,
    status                VARCHAR(12)   NOT NULL,
    transaction_reference VARCHAR(40)   NOT NULL,
    CONSTRAINT fk_payments_order
        FOREIGN KEY (order_id) REFERENCES orders (order_id),
    CONSTRAINT uq_payments_txn UNIQUE (transaction_reference),
    CONSTRAINT ck_payments_amount CHECK (amount >= 0),
    CONSTRAINT ck_payments_method CHECK (payment_method IN
        ('CREDIT_CARD', 'DEBIT_CARD', 'PAYPAL', 'BANK_TRANSFER', 'CASH_ON_DELIVERY')),
    CONSTRAINT ck_payments_status CHECK (status IN
        ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED'))
);

-- ----------------------------------------------------------------------------
-- shipments
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS shipments (
    shipment_id     INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        INTEGER      NOT NULL,
    shipment_date   TIMESTAMPTZ,
    delivery_date   TIMESTAMPTZ,
    carrier         VARCHAR(40),
    tracking_number VARCHAR(50),
    status          VARCHAR(12)  NOT NULL,
    CONSTRAINT fk_shipments_order
        FOREIGN KEY (order_id) REFERENCES orders (order_id),
    CONSTRAINT uq_shipments_tracking UNIQUE (tracking_number),
    CONSTRAINT ck_shipments_status CHECK (status IN
        ('PREPARING', 'SHIPPED', 'IN_TRANSIT', 'DELIVERED', 'RETURNED'))
);

-- ----------------------------------------------------------------------------
-- Indices  (FK, fechas, estados, email, relaciones frecuentes)
-- Postgres NO indexa las FK automaticamente: se declaran de forma explicita.
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS ix_customers_status       ON customers (status);
CREATE INDEX IF NOT EXISTS ix_customers_city         ON customers (city);
CREATE INDEX IF NOT EXISTS ix_customers_country      ON customers (country);
CREATE INDEX IF NOT EXISTS ix_customers_registration ON customers (registration_date);

CREATE INDEX IF NOT EXISTS ix_addresses_customer     ON addresses (customer_id);

CREATE INDEX IF NOT EXISTS ix_products_category      ON products (category_id);
CREATE INDEX IF NOT EXISTS ix_products_status        ON products (status);
CREATE INDEX IF NOT EXISTS ix_products_price         ON products (price);

CREATE INDEX IF NOT EXISTS ix_orders_customer        ON orders (customer_id);
CREATE INDEX IF NOT EXISTS ix_orders_date            ON orders (order_date);
CREATE INDEX IF NOT EXISTS ix_orders_status          ON orders (status);
CREATE INDEX IF NOT EXISTS ix_orders_address         ON orders (shipping_address_id);

CREATE INDEX IF NOT EXISTS ix_order_items_order      ON order_items (order_id);
CREATE INDEX IF NOT EXISTS ix_order_items_product    ON order_items (product_id);

CREATE INDEX IF NOT EXISTS ix_payments_order         ON payments (order_id);
CREATE INDEX IF NOT EXISTS ix_payments_status        ON payments (status);
CREATE INDEX IF NOT EXISTS ix_payments_method        ON payments (payment_method);
CREATE INDEX IF NOT EXISTS ix_payments_date          ON payments (payment_date);

CREATE INDEX IF NOT EXISTS ix_shipments_order        ON shipments (order_id);
CREATE INDEX IF NOT EXISTS ix_shipments_status       ON shipments (status);
CREATE INDEX IF NOT EXISTS ix_shipments_date         ON shipments (shipment_date);
